balena-io/open-balena-registry

.github/CODEOWNERS

Connects-to: #60
Signed-off-by: Heds Simons <heds@balena.io>

codeowners: Add	@dfunckt, @Page- & @hedss

---

Dockerfile

Update registry to v2.7.1

---

Dockerfile
config/confd/templates/docker-registry.yml.tmpl

Enable redis cache

---

.gitignore
package-lock.json
repo.yml

Add repo.yml for future open-balena-base updates

---

.versionbot/CHANGELOG.yml

Signed-off-by: Rich Bayliss <rich@balena.io>

versionbot: Add CHANGELOG.yml to allow nested changelogs

---

config/services/balena-registry.service

Signed-off-by: Matthew McGinn <matthew@balena.io>

systemd: move StartLimitIntervalSec to proper section

---

Dockerfile
config/confd/templates/redis.conf.tmpl
config/services/redis-server.service
config/services/redis-server.service.d/restart.conf

Fix redis-server startup

---

.github/CODEOWNERS

Remove Hedley from CODEOWNERS

---

config/confd/templates/docker-registry.yml.tmpl

Signed-off-by: Carlo Miguel Cruz <carloc@balena.io>

Enable deletion of old entries when using as pull through cache.

---

config/services/balena-registry.service

Increase soft-limit of maximum number of open files

---

config/confd/templates/docker-registry.yml.tmpl

Add configuration for the redis cache pool

---

Dockerfile

Update registry to v2.8.0

---

config/confd/templates/docker-registry.yml.tmpl

Allow configuring log level and default to `error` level

---

config/confd/templates/docker-registry.yml.tmpl

Add config to disable upload purging

---

.github/workflows/flowzone.yml

Enable external contributors

---

config/confd/templates/docker-registry.yml.tmpl

Fix syntax

---

Dockerfile

update docker/distribution to v2.8.3

---

config/confd/templates/docker-registry.yml.tmpl

Required by: https://app.secureframe.com/tests/769a45fe-40c7-426f-819b-a037dec98fec (ISO27k1/SOC2)
Requires: https://github.com/balena-io/environment-staging/pull/2995
Manually tested: https://github.com/balena-io/e2e/actions/runs/7806193636/job/21292033924
change-type: patch

enable S3 encryption config toggle

---

config/confd/conf.d/logentries.conf.toml
config/confd/templates/logentries.conf.tmpl

Remove unused logentries configs

---

repo.yml

Fix nested changelog for open-balena-base updates

---

config/confd/templates/docker-registry.yml.tmpl

Add the ability to specify s3 storage class

---

config/confd/templates/docker-registry.yml.tmpl

Fix v3 redis config

---

Dockerfile

Update open-balena-base from 18.0.41 to 19.0.0

Update open-balena-base to 19.0.0
